### ISSUE TITLE
Bug: Personal nameplates buffs not inheriting any checkbox options

### ISSUE THREAD

**Issue by fearkite** [Bodify/BetterBlizzPlates#18]
Hey mate!

I've noticed that personal nameplates buffs are not inheriting any checkbox options, as per below. 

![image](https://github.com/user-attachments/assets/afb805ad-dbf1-4f40-b126-b722a97c7138)

![image](https://github.com/user-attachments/assets/4d581b47-e7d8-4991-808b-5fe16b71396f)

**Comment by Bodify** [comment]
Hey! This is actually by design. Poor design but design nonetheless. A lot of people complained that the glow was on the personal nameplate as well so I decided back then to just make it not show on the personal bar.

The personal bar has not been getting a lot of love (I don't use it) but I do want to start showing it some love in the future. Right now I am busy improving a lot of things behind the scenes, also other features, but once all of this is in place the nameplate auras section of BBP is something I want to work on and improve, adding back glow on the personal bar (optionally) among other things.
When exactly this is I can't promise but probably not until a couple of months or more honestly. It is a ton of work and I do it all for free on my spare time so I feel a break is due soon where I can relax.
