### ISSUE TITLE
nameplate philosophy

### ISSUE THREAD

**Issue by tidehunter1** [Bodify/BetterBlizzPlates#2]
Hey, nice addition to the nameplate ecosystem, you've got some nice ideas there.
bit of a long one here.
I too started my own project for myself based on blizzard plates similar to yours, it wasn't until deep within my project I realized why most projects redraw the nameplates, performance being the main one
the biggest reason for me was because of one line of code: "C_NamePlate.SetNamePlateFriendlySize(1,1)"
this particular line allows changing of friendly nameplates to small size even while in dungeons, it also prevents friendly nameplates stacking with enemy plates, however it has a major drawback, when a plate goes from friendly to hostile there is no way to resize the blizzard plate to a normal hostile size without tainting, there's another line of code that's popular these days that simply hides all nameplate 'bars' with the name still visible but I'm not sold on this idea since you cant directly change the friendly nameplate "name" in dungeons and therefore everyone is "purple", it also messes with the m+ affix afflicted and its best to keep its bar intact.

Of the many nameplate projects that exist, there are always one or two good ideas that don't exist in other projects, one particular project is NameplateKAI. I find it visually pleasing in many aspects but there are key features it doesn’t have such as castbar targeted. Its main selling point is predefined unit plate coloring and cleverly colors the units name based on threat.
So if the unit's name is colored red, it's either targeting you or about to, green > yellow = safe.

**Castbar:**
In a M+ key, there are interrupts you must stop and some you can let through, one of Platers popular profiles colorizes the different important casts which obviously has to be maintained every season.

**Auras:**
When attempting to implement my own nameplate aura system I realized quickly I already had an aura system far superior to anything I could create, weakauras with many wago projects better suited to specific specs. I play ret paladin so all i really need to see is cc/interrupts in large size. I ended up switching to a better aura system "OmniAuras", its performance acts as if the addon is idle, your project reminds me of it.

**Quest Marker:**
Two nameplate projects come to mind, QuestPlates and NDui, instead of displaying a marker icon, their implementation has the quest progress tracked on the plate itself, so typically 1 to X is displayed somewhere on the plate.

Essentially what I ended up doing is taking the best bits out of many addons and incorporated it into my own.

Some other tricks you can do:
C_CVar.SetCVar("nameplateOverlapV", 0.6) –tightens the stacking of nameplates on each other
Set these based on conditions
C_CVar.SetCVar("nameplateOccludedAlphaMult", 0) --hide in dungeons, spam units behind walls hidden.
C_CVar.SetCVar("nameplateOccludedAlphaMult", 1) --arena only, view plates behind pillars
C_CVar.SetCVar("nameplateOccludedAlphaMult", 0.4) --default, worldzones

**Comment by Bodify** [comment]
Hey! Thank you for the input.
I designed BetterBlizzPlates with authenticity, performance and PvP in mind.
I agree on that for example using weakauras for debuffs/buffs on nameplates is a better and easier solution that allows for ton of customization. I do so myself, but with BetterBlizzPlates I want to try and add to what is already there and stick to the original and avoid adding extra features for things that already exist if I can (and want to).

I'm unfamiliar with how PvE works and what options are out there and quite frankly I do not care either.
I do want my AddOn to be good though so I'll consider anything I personally find either smart or reasonable and attempt to add it if I figure I'll enjoy doing it.

I'm aware that there are a lot of profiles and predefined settings out there for various AddOns but these require knowledge of the environment and time and effort to set up. Time and effort that at this time I do not wish to put down.
If I inadvertently get closer to such a system by doing other features I might eventually do it but so far no plans for it.

To go over and address some points you made;

- C_NamePlate.SetNamePlateFriendlySize(1,1) and "when a plate goes from friendly to hostile there is no way to resize the blizzard plate to a normal hostile size without tainting"

I kind of use this in my code as well, or the "height" setting at least. There's a checkbox called "Clickthrough nameplates" that sets it to (userDefinedX, 1). I'm aware about the "friendly to hostile" nameplate size glitch and it's something I've just said to myself "It's blizzards code, not mine, not my problem". A quick (but annoying) workaround is to hide your UI (Alt+Z by default) and show it again.

- Castbar and Auras

I've already touched on this so in short: I want to keep it as authentic to the default nameplates as possible and there are other AddOns you can use together with BetterBlizzPlates if you don't like that (Or use a different nameplate AddOn entirely)

- Quest Marker

I tried out QuestPlates. I think it was kind of neat but also a bit cluttering at the same time. I added a simple quest indicator that I'm happy with. For you or anyone else reading this feel free to use BetterBlizzPlates together with QuestPlates if you want a more advanced quest indicator.

- CVar tricks

This idea I really liked and might add eventually. Although I do see some potential risks walking around a corner into a cluster of NPCs because you didn't see them lol.
