### ISSUE TITLE
Nameplate Auras: Important Glow doesn't work on PRD

### ISSUE THREAD

**Issue by kbarrette** [Bodify/BetterBlizzPlates#23]
Looks like the "Important Glow" feature for nameplate auras doesn't work on the personal resource display. "Pandemic Glow" DOES work. I'll try to figure out what's broken and submit a patch, but I thought I'd log an issue first.

**Comment by Bodify** [comment]
Hey! This is actually intended for the time being (because it was requested by multiple people and I made it as a quickfix). It is not explained anywhere though which leads to confusion. Pandemic has been forgotten about so that is unintended. I plan on making things more customizeable in the future with separate settings for the different nameplate types etc but for now it will remain the same for a while until I get time to to work on it.

**Comment by kbarrette** [comment]
@Bodify got it - will close this!
