### ISSUE TITLE
Lua error message in chat on Login

### ISSUE THREAD

**Issue by XimmortalAresX** [Bodify/BetterBlizzPlates#6]
![1](https://github.com/Bodify/BetterBlizzPlates/assets/151626582/4f022e20-deaf-466e-b0e0-5bb6ac828919)
 This message pops up in my chat when i first login to WoW, reloading the UI doesn't cause the message to pop up again, only when i first login, aside from the message i haven't noticed any problem caused from this message, but i just thought i should let you know this is happening just in case it starts causing problems at some point down the line.

**Comment by Bodify** [comment]
Hey! Some other person had issues with a login lua error due to the LibOpenRaid lib I use as well. They told me that updating to a newer alpha version solved it for them so I figured I could just add that version to BBP as well.
Are you on the newer version of BBP where this alpha version was added?

**Comment by Bodify** [comment]
Great! Yea I'm not good with patch notes so I think that was the one where I updated it in yeah so makes sense!
